# Tensorflow Crash Course - Deep Learning in Python For Beginners


https://www.youtube.com/watch?v=72s6hJwyfDg

In [1]:
import tensorflow as tf

# 1. Is TF built with CUDA support?
print("Built with CUDA:", tf.test.is_built_with_cuda())

# 2. How many GPUs does TF see?
gpus = tf.config.list_physical_devices("GPU")
print("Num GPUs:", len(gpus))
print("GPU devices:", gpus)

# 3. Optional: show all devices (CPU + GPU)
from tensorflow.python.client import device_lib
print("All local devices:", device_lib.list_local_devices())

Built with CUDA: False
Num GPUs: 0
GPU devices: []
All local devices: [name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1602339315910040468
xla_global_id: -1
]


In [2]:
import sys, os, tensorflow as tf

print("Python executable:", sys.executable)
print("LD_LIBRARY_PATH set:", bool(os.environ.get("LD_LIBRARY_PATH")))
print("TF version:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices("GPU"))

Python executable: c:\Users\jc\anaconda3\envs\ece\python.exe
LD_LIBRARY_PATH set: False
TF version: 2.21.0
GPUs: []


In [3]:
import tensorflow as tf
import numpy as np

print("GPUs:", tf.config.list_physical_devices("GPU"))

# Simple model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu", input_shape=(5,)),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer="adam", loss="mse")

# Dummy data
X = np.random.randn(100, 5).astype("float32")
y = np.random.randn(100, 1).astype("float32")

# Train
model.fit(X, y, epochs=3, batch_size=16)

GPUs: []
Epoch 1/3


c:\Users\jc\anaconda3\envs\ece\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3547  
Epoch 2/3
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3173 
Epoch 3/3
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2806 


### CODE ABOVE TESTS GPU ON WINDOWS

### CODE BELOW IS LEARNING FROM VIDEO

In [14]:
import tensorflow as tf
import pandas as pd

In [15]:
pd.set_option('display.max_rows', None)      # Show all rows
pd.set_option('display.max_columns', None)   # Show all columns

In [6]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [7]:
X_train.shape

(60000, 28, 28)

In [8]:
y_train.shape

(60000,)

In [9]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

### Preprocess the data

In [ ]:
X_train, X_test = X_train / 255.0, X_test / 255.0

In [18]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [19]:
y_train

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

### Build Neural Network

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout

In [21]:
model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

In [23]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction # logits. Softmas would make sure probabilities go to 100%. Numerically unstable to do the loss function.
# Apply softmax just for the reasoning part.

array([[-0.06086389, -0.8643354 ,  0.63355774,  0.37189084, -0.0673745 ,
         0.3850008 ,  0.19393423,  0.42160034, -0.06550023,  0.42485005]],
      dtype=float32)

In [24]:
tf.nn.softmax(nonsense_prediction).numpy()

array([[0.07646345, 0.03423818, 0.15312192, 0.11786826, 0.07596724,
        0.11942368, 0.09865323, 0.1238755 , 0.07610977, 0.12427871]],
      dtype=float32)

In [25]:
tf.nn.softmax(nonsense_prediction).numpy().sum()

np.float32(0.99999994)

In [26]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [28]:
loss_fn = SparseCategoricalCrossentropy(from_logits=True)
# -tf.math.log(1/10)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.125077724456787>

In [29]:
from tensorflow.keras.optimizers import Adam

In [30]:
optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [31]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8970 - loss: 0.3451
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9259 - loss: 0.2557
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9312 - loss: 0.2394
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9339 - loss: 0.2342
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9386 - loss: 0.2211
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9413 - loss: 0.2182
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9418 - loss: 0.2122
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9435 - loss: 0.2071
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9443 - loss: 0.2031
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9469 - loss: 0.1971


In [32]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.9584 - loss: 0.2123


[0.21234509348869324, 0.9584000110626221]

Can improve performance by increasing neurons in dense layer.
Try 128 instead of 64. Called hyperparameter tuning (also changing activators, optimizers, etc.)

In [33]:
model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

from tensorflow.keras.losses import SparseCategoricalCrossentropy

loss_fn = SparseCategoricalCrossentropy(from_logits=True)

from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10)

model.evaluate(X_test, y_test)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9100 - loss: 0.3175
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9405 - loss: 0.2302
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9488 - loss: 0.2020
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9512 - loss: 0.1949
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9524 - loss: 0.1911
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9552 - loss: 0.1873
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9577 - loss: 0.1629
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9577 - loss: 0.1735
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9598 - loss: 0.1695
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9601 - loss: 0.1688
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9594 - loss: 0.2509


[0.25094273686408997, 0.9593999981880188]

In [35]:
tf.argmax(tf.nn.softmax(model(X_test[:1])).numpy(), axis=1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>

In [36]:
y_test[:1]

array([7], dtype=uint8)

### Regression Task

In [37]:
import pandas as pd

df = pd.read_csv('housing.csv')

In [39]:
df.head(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X, y = df.drop('MedHouseVal', axis=1), df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [42]:
X_train_scaled

array([[-0.326196  ,  0.34849025, -0.17491646, ...,  0.05137609,
        -1.3728112 ,  1.27258656],
       [-0.03584338,  1.61811813, -0.40283542, ..., -0.11736222,
        -0.87669601,  0.70916212],
       [ 0.14470145, -1.95271028,  0.08821601, ..., -0.03227969,
        -0.46014647, -0.44760309],
       ...,
       [-0.49697313,  0.58654547, -0.60675918, ...,  0.02030568,
        -0.75500738,  0.59946887],
       [ 0.96545045, -1.07984112,  0.40217517, ...,  0.00707608,
         0.90651045, -1.18553953],
       [-0.68544764,  1.85617335, -0.85144571, ..., -0.08535429,
         0.99543676, -1.41489815]], shape=(16512, 8))

In [44]:
X_train_scaled.shape

(16512, 8)

In [45]:
model = Sequential()
model.add(Input((8,)))
model.add(Dense((64), activation='relu'))
model.add(Dense((64), activation='relu'))
model.add(Dense(1))

In [46]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score'])

In [47]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - loss: 0.7451 - mae: 0.5922 - r2_score: 0.4426
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 953us/step - loss: 0.3873 - mae: 0.4411 - r2_score: 0.7102
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - loss: 0.3812 - mae: 0.4280 - r2_score: 0.7148
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3464 - mae: 0.4142 - r2_score: 0.7408
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3337 - mae: 0.4048 - r2_score: 0.7503
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3220 - mae: 0.3961 - r2_score: 0.7591
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3303 - mae: 0.3927 - r2_score: 0.7529
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3066 - mae: 0.3845 - r2_score: 0.7706
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3004 - mae: 0.3805 - r2_score: 0.7753
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2962 - mae: 0.3770 - r2_score: 

In [48]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3167 - mae: 0.3932 - r2_score: 0.7583


[0.316691517829895, 0.39318424463272095, 0.7583261728286743]

In [49]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64