# PyTorch Crash Course: Deep Learning in Python

https://www.youtube.com/watch?v=uq7sbUlIDR8

In [1]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1

In [6]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 5080 Laptop GPU'

In [7]:
torch.cuda.device(0)

### Tensors

In [11]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
tensor = torch.Tensor([[1,2,3], [4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [15]:
arr.sum()

np.int64(21)

In [16]:
tensor.sum()

tensor(21.)

In [17]:
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
torch.ones((2, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
np.random.random((2, 4))

array([[0.43915629, 0.02406455, 0.05938413, 0.31725964],
       [0.30068643, 0.75754341, 0.72735897, 0.7501108 ]])

In [21]:
torch.rand((2,4))

tensor([[0.7907, 0.5768, 0.7384, 0.9333],
        [0.4582, 0.4944, 0.7593, 0.6170]])

In [22]:
arr.shape

(2, 3)

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr.device

'cpu'

In [25]:
tensor.shape

torch.Size([2, 3])

In [26]:
tensor.dtype

torch.int64

In [27]:
tensor.device

device(type='cpu')

In [ ]:
# Will throw an error
# arr.to_device('cuda')

ValueError: Unsupported device: cuda. Only 'cpu' is accepted.

In [30]:
tensor = tensor.to('cuda')

In [31]:
tensor.sum()

tensor(21, device='cuda:0')

In [32]:
# Convert from GPU to CPU
tensor.cpu().numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
device = 'cude' if torch.cuda.is_available() else 'cpu'

# To send to a device
# .to(device)


SyntaxError: invalid syntax (2433131579.py, line 3)

### PyTorch AutoGrad

In [43]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2

In [44]:
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [45]:
# Back propagates hte gradient depending on weight
f.backward(gradient=torch.tensor([1,1]))

In [46]:
print(a.grad)

tensor([36., 81.])


In [47]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [48]:
print(b.grad)

tensor([-12.,  -8.])


In [49]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

### Loading Datasets in PyTorch

In [50]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [53]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [54]:
X_train_scaled

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]], shape=(455, 30))

In [56]:
y_train

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,

In [57]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)  # Add an extra dimension for the target
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)  # Add an extra dimension for the target

In [58]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)

In [59]:
X_train_scaled_tensor.shape

torch.Size([455, 30])

In [ ]:
# Shape has 30, so use batch_size=32
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [ ]:
'''
class BCNet(nn.Module):
    def __init__(self):
        super(BCNet, self).__init__()
        self.fc1 = nn.Linear(30, 16)  # Input layer to hidden layer
        self.fc2 = nn.Linear(16, 8)   # Hidden layer to another hidden layer
        self.fc3 = nn.Linear(8, 1)    # Hidden layer to output layer

    def forward(self, x):
        x = F.relu(self.fc1(x))       # Activation function for first hidden layer
        x = F.relu(self.fc2(x))       # Activation function for second hidden layer
        x = torch.sigmoid(self.fc3(x))  # Sigmoid activation for output layer
        return x
'''

class BCNet(nn.Module):
    def __init__(self):
        super(BCNet, self).__init__()
        self.fc1 = nn.Linear(30, 64)  # Input layer to hidden layer
        self.fc2 = nn.Linear(64, 32)   # Hidden layer to another hidden layer
        self.fc3 = nn.Linear(32, 1)    # Hidden layer to output layer

    def forward(self, x):
        x = F.relu(self.fc1(x))       # Activation function for first hidden layer
        x = F.relu(self.fc2(x))       # Activation function for second hidden layer
        x = F.sigmoid(self.fc3(x))  # Sigmoid activation for output layer
        return x