# Tensorflow Crash Course - Deep Learning in Python For Beginners


https://www.youtube.com/watch?v=72s6hJwyfDg

In [1]:
# For GPU RTX 5080
import os
os.environ["XLA_FLAGS"] = "--xla_gpu_enable_triton_gemm=false --xla_gpu_autotune_level=0"
os.environ["TF_CUDNN_USE_AUTOTUNE"] = "false"
os.environ["TF_USE_TRITON_GEMM"] = "0"

In [2]:
import tensorflow as tf

print("TF version:", tf.__version__)

gpus = tf.config.list_physical_devices("GPU")
print("GPUs detected by TensorFlow:", gpus)

if gpus:
    for i, gpu in enumerate(gpus):
        print(f"  GPU {i}: {gpu.name}")
else:
    print("No GPU found; TensorFlow will use CPU.")

I0000 00:00:1788728817.449090   26588 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1788728817.496076   26588 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/jc/miniconda3/envs/py312/lib/python3.12/site-packages/requests/__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
I0000 00:00:1788728819.425674   26588 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off

TF version: 2.21.0
GPUs detected by TensorFlow: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
  GPU 0: /physical_device:GPU:0


W0000 00:00:1788728823.782054   26588 gpu_device.cc:2459] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.


In [3]:
import tensorflow as tf

gpus = tf.config.list_physical_devices("GPU")
if not gpus:
    raise RuntimeError("No GPU detected")

tf.config.set_visible_devices(gpus[0], "GPU")

with tf.device("/GPU:0"):
    a = tf.random.uniform((1000, 1000))
    b = tf.random.uniform((1000, 1000))
    c = tf.matmul(a, b)

print(tf.__version__)
print("MatMul on GPU succeeded, result shape:", c.shape)

W0000 00:00:1788728823.797757   26588 gpu_device.cc:2459] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1788728824.285317   26588 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13245 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5080 Laptop GPU, pci bus id: 0000:64:00.0, compute capability: 12.0a


2.21.0
MatMul on GPU succeeded, result shape: (1000, 1000)


### CODE ABOVE TESTS GPU ON WINDOWS

### CODE BELOW IS LEARNING FROM VIDEO

In [4]:
import tensorflow as tf
import pandas as pd

In [5]:
pd.set_option('display.max_rows', None)      # Show all rows
pd.set_option('display.max_columns', None)   # Show all columns

In [6]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
X_train.shape

(60000, 28, 28)

In [8]:
y_train.shape

(60000,)

In [9]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

### Preprocess the data

In [10]:
X_train, X_test = X_train / 255.0, X_test / 255.0

In [11]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [12]:
y_train

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

### Build Neural Network

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout

In [14]:
model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

In [15]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction # logits. Softmas would make sure probabilities go to 100%. Numerically unstable to do the loss function.
# Apply softmax just for the reasoning part.

array([[-0.27884325, -0.5082586 ,  0.5060642 , -0.37934357,  0.4322266 ,
         0.5681212 ,  0.22219913,  1.1831774 ,  0.20301211, -0.18328893]],
      dtype=float32)

In [16]:
tf.nn.softmax(nonsense_prediction).numpy()

array([[0.05572656, 0.04430252, 0.12216398, 0.05039825, 0.11346866,
        0.12998529, 0.09197339, 0.24044165, 0.09022551, 0.06131418]],
      dtype=float32)

In [17]:
tf.nn.softmax(nonsense_prediction).numpy().sum()

np.float32(0.99999994)

In [18]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [19]:
loss_fn = SparseCategoricalCrossentropy(from_logits=True)
# -tf.math.log(1/10)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0403339862823486>

In [20]:
from tensorflow.keras.optimizers import Adam

In [21]:
optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [22]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10


I0000 00:00:1788728827.100523   26772 service.cc:153] XLA service 0x7cc020042610 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1788728827.100571   26772 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 5080 Laptop GPU, Compute Capability 12.0a (Driver: 13.4.0; Runtime: 12.9.0; Toolkit: 12.5.0; DNN: 9.25.1)
I0000 00:00:1788728827.113678   26772 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1788728827.174883   26772 cuda_dnn.cc:461] Loaded cuDNN version 92501
I0000 00:00:1788728827.199585   26772 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1024__.11


  55/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7097 - loss: 0.8992

I0000 00:00:1788728827.702541   26772 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8967 - loss: 0.3424
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9268 - loss: 0.2506
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9344 - loss: 0.2307
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9369 - loss: 0.2224
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9411 - loss: 0.2118
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9423 - loss: 0.2110
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9446 - loss: 0.2031
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9445 - loss: 0.2021
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9464 - loss: 0.1955
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9473 - loss: 0.1952


In [23]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9635 - loss: 0.1827


[0.1826544851064682, 0.9635000228881836]

Can improve performance by increasing neurons in dense layer.
Try 128 instead of 64. Called hyperparameter tuning (also changing activators, optimizers, etc.)

In [24]:
model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

from tensorflow.keras.losses import SparseCategoricalCrossentropy

loss_fn = SparseCategoricalCrossentropy(from_logits=True)

from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10)

model.evaluate(X_test, y_test)

Epoch 1/10


I0000 00:00:1788728883.508592   26770 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_78920__.12


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9118 - loss: 0.3162
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9399 - loss: 0.2297
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9472 - loss: 0.2067
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9510 - loss: 0.1992
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9552 - loss: 0.1828
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9566 - loss: 0.1849
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9578 - loss: 0.1718
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9572 - loss: 0.1745
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9608 - loss: 0.1723
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9606 - loss: 0.1686
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9577 - loss: 0.2572


[0.2572481334209442, 0.9577000141143799]

In [25]:
tf.argmax(tf.nn.softmax(model(X_test[:1])).numpy(), axis=1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>

In [26]:
y_test[:1]

array([7], dtype=uint8)

### Regression Task

In [27]:
import pandas as pd

df = pd.read_csv('housing.csv')

In [28]:
df.head(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611


In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X, y = df.drop('MedHouseVal', axis=1), df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
X_train_scaled

array([[-0.326196  ,  0.34849025, -0.17491646, ...,  0.05137609,
        -1.3728112 ,  1.27258656],
       [-0.03584338,  1.61811813, -0.40283542, ..., -0.11736222,
        -0.87669601,  0.70916212],
       [ 0.14470145, -1.95271028,  0.08821601, ..., -0.03227969,
        -0.46014647, -0.44760309],
       ...,
       [-0.49697313,  0.58654547, -0.60675918, ...,  0.02030568,
        -0.75500738,  0.59946887],
       [ 0.96545045, -1.07984112,  0.40217517, ...,  0.00707608,
         0.90651045, -1.18553953],
       [-0.68544764,  1.85617335, -0.85144571, ..., -0.08535429,
         0.99543676, -1.41489815]], shape=(16512, 8))

In [32]:
X_train_scaled.shape

(16512, 8)

In [33]:
model = Sequential()
model.add(Input((8,)))
model.add(Dense((64), activation='relu'))
model.add(Dense((64), activation='relu'))
model.add(Dense(1))

In [34]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score'])

In [35]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
  1/516 ━━━━━━━━━━━━━━━━━━━━ 14:04 2s/step - loss: 4.6284 - mae: 1.7340 - r2_score: -1.9301

I0000 00:00:1788728946.361024   26773 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_156988__.12


516/516 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 0.7008 - mae: 0.5741 - r2_score: 0.4757
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3886 - mae: 0.4412 - r2_score: 0.7093
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3574 - mae: 0.4244 - r2_score: 0.7326
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3437 - mae: 0.4133 - r2_score: 0.7429
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3358 - mae: 0.4022 - r2_score: 0.7488
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3196 - mae: 0.3941 - r2_score: 0.7609
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3135 - mae: 0.3880 - r2_score: 0.7655
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3009 - mae: 0.3807 - r2_score: 0.7749
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2992 - mae: 0.3773 - r2_score: 0.7762
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2967 - mae: 0.3760 - r2_score: 0.7780


In [36]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3020 - mae: 0.3740 - r2_score: 0.7695


[0.3020136058330536, 0.3740246593952179, 0.7695271968841553]

In [37]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64